### ISSUE TITLE
buffer_t.alloc is redundant ?

### ISSUE THREAD

**Issue by marcomorain** [clibs/buffer#11]
I'm confused by the `.alloc` member of `buffer_t` – it seems to always point to the same memory as `.data`. 

One reason to have separate pointers for data and allocated data would be if the buffer could be passed in some initial space to use. Maybe something like this:

```C
char buf[BUFFER_DEFAULT_SIZE];
struct buffer_t buffer;
buffer_init(buf, BUFFER_DEFAULT_SIZE);
```

after which `buffer.data` would point to the memory at `buf`, but `buffer.alloc` would be null. After pushing more than `BUFFER_DEFAULT_SIZE` characters into the buffer I would expect a realloc, after which `.data` and `.alloc` would point at the same piece of heap memory.

This is not how the code works though – the buffer is always heap allocated.

Possbile solutions:
- allow user to pass in a block if initial memory (that `.alloc` would not reference)
- remove the `.alloc` member

/cc @tj

**Comment by stephenmathieson** [comment]
how could we do [this](https://github.com/clibs/buffer/blob/master/buffer.c#L92-L97) without two pointers?

**Comment by marcomorain** [comment]
You had me _so_ confused there. I think you meant to link [here](https://github.com/clibs/buffer/blob/master/buffer.c#L287-L291)!

**Comment by marcomorain** [comment]
So it turns out that the use of `alloc` and `data` is to allow efficient left-trimming. Thanks @stephenmathieson
