### ISSUE TITLE
Buffer Prepend Does not Copy Correctly

### ISSUE THREAD

**Issue by phoenixpinpoint** [clibs/buffer#15]
Hello all, 
I have come across an issue where for what appears to be no good reason buffer_prepend doesn't work as expected. I used the test.c buffer_prepend test as a template: 
```C
    buffer_t *buf = buffer_new();
    buffer_append(buf, " World");
    buffer_prepend(buf, "Hello");
    printf("HW: %s\n", buf->data);
```
Which returns: 
```bash
HW: Hello World
```
As expected, but the following:
```C
    buffer_t *file = buffer_new();
    buffer_append(file, "layout.bk.html");
    buffer_prepend(file, "./example/");
    printf("BASED: %s\n", file->data);
```
returns:
```bash
BASED: ./example/layout.bk.h
```
Cutting off the "tml" on the end of the file path. 

I have played with the memmove function call and the only way I could get it to be reasonable was to have it copy the length of the "needed" length and not the length of the string to prepend. This could cause a write into memory not allocated for that buffer, so that is right out.

Not sure where to go from here. 
Thanks,
Adam.

**Comment by diasbruno** [comment]
It's moving just the size of the string been prepended and not the actual size to be moved.
